version: '3.8'

services:
  redis:
    image: redis:7.2
    container_name: redisDB
    ports:
      - "6379:6379"
    volumes:
      - redisDB-data:/data
    restart: unless-stopped

  postgres:
    image: postgres:15
    container_name: postgres
    environment:
      POSTGRES_USER: users
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: auth_db
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  redis-data:
  postgres-data: